### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by triwats** [gaieges/flexget-daemon#10]
Hi, I'm looking to get some improvements into this, but I am wondering if you are still actively willing to accept PRs?

Please let me know. I have forked it, but may start fresh to remove fork complexity if it's unlikely to get merged in. Thank you! :)

**Comment by gaieges** [comment]
Sure! Would love a contribution. I still use it pretty frequently too, so would be happy to give feedback during regular usage

**Comment by triwats** [comment]
:+1: super quick response too! I'll see what I can cobble together.
